"""
IPCC Report Summarizer & Translator — Web App
-----------------------------------------------
Gradio interface for the same pipeline as summarize_report.py:
upload a PDF, pick a page range, get a plain-language English summary
plus Yoruba, Hausa, and Igbo translations, generated by Claude.

Deployment target: Hugging Face Spaces (free tier).
Set ANTHROPIC_API_KEY as a Space secret — never hardcode it here.
"""

import json
import os

import gradio as gr
from anthropic import Anthropic
from pypdf import PdfReader

MODEL = "claude-sonnet-5"
MAX_CHARS = 12000

client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))


def extract_pdf_text(pdf_path: str, start_page: int, end_page: int) -> str:
    reader = PdfReader(pdf_path)
    total_pages = len(reader.pages)

    start = max(start_page - 1, 0)
    end = min(end_page, total_pages)

    if start >= end:
        raise ValueError(f"Invalid page range for a {total_pages}-page document.")

    text_parts = [reader.pages[i].extract_text() or "" for i in range(start, end)]
    full_text = "\n".join(text_parts).strip()

    if not full_text:
        raise ValueError(
            "No extractable text found in that page range. "
            "This PDF may be scanned/image-based and would need OCR first."
        )

    return full_text[:MAX_CHARS]


def summarize_and_translate(pdf_file, start_page, end_page):
    if pdf_file is None:
        return "Please upload a PDF first.", "", "", "", ""

    try:
        excerpt = extract_pdf_text(pdf_file.name, int(start_page), int(end_page))
    except Exception as e:
        return f"**Error reading PDF:** {e}", "", "", "", ""

    prompt = f"""You are helping a community organization make an IPCC climate
report excerpt accessible to non-technical residents who are not scientists.

Given the excerpt below, respond ONLY with a JSON object (no markdown fences,
no preamble) with exactly these keys:

- "english": a plain-language summary in 4-6 sentences, no jargon
- "yoruba": a Yoruba translation of that same plain-language summary
- "hausa": a Hausa translation of that same plain-language summary
- "igbo": an Igbo translation of that same plain-language summary
- "key_terms": a short list (3-5 items) of technical terms that were
  simplified or omitted

Report excerpt:
{excerpt}
"""

    try:
        response = client.messages.create(
            model=MODEL,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )
        text_block = next((b.text for b in response.content if b.type == "text"), "{}")
        cleaned = text_block.strip().removeprefix("```json").removesuffix("```").strip()
        result = json.loads(cleaned)
    except Exception as e:
        return f"**Error calling Claude:** {e}", "", "", "", ""

    terms = "\n".join(f"- {t}" for t in result.get("key_terms", []))

    return (
        result.get("english", ""),
        result.get("yoruba", ""),
        result.get("hausa", ""),
        result.get("igbo", ""),
        terms,
    )


with gr.Blocks(title="IPCC Report Summarizer & Translator") as demo:
    gr.Markdown(
        """
        # IPCC Report Summarizer & Translator
        Upload a real IPCC report PDF, pick a page range, and get a
        plain-language summary in English, Yoruba, Hausa, and Igbo — generated by Claude.

        **Note:** Yoruba, Hausa, and Igbo outputs are machine translations and
        have not yet been reviewed by native speakers. Treat as a first draft.
        """
    )

    with gr.Row():
        pdf_input = gr.File(label="Upload IPCC report PDF", file_types=[".pdf"])
        with gr.Column():
            start_page = gr.Number(label="Start page", value=1, precision=0)
            end_page = gr.Number(label="End page", value=3, precision=0)

    run_btn = gr.Button("Generate summary", variant="primary")

    english_out = gr.Textbox(label="Plain-language summary (English)", lines=6)
    yoruba_out = gr.Textbox(label="Yoruba translation", lines=6)
    hausa_out = gr.Textbox(label="Hausa translation", lines=6)
    igbo_out = gr.Textbox(label="Igbo translation", lines=6)
    terms_out = gr.Markdown(label="Terms simplified or omitted")

    run_btn.click(
        fn=summarize_and_translate,
        inputs=[pdf_input, start_page, end_page],
        outputs=[english_out, yoruba_out, hausa_out, igbo_out, terms_out],
    )

if __name__ == "__main__":
    demo.launch()
